# Generated by Django 2.2.2 on 2019-07-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='price',
        ),
    ]
