# Generated by Django 2.2.2 on 2019-07-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190721_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=1000),
        ),
    ]
