# Generated by Django 2.2.2 on 2019-07-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cart_coupon'),
        ('orders', '0005_remove_order_coupon'),
        ('products', '0004_auto_20190721_0028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
