# Generated by Django 2.2.2 on 2019-07-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190720_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
